changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Breaking Changes and Deprecations
      labels:
        - "topic: bc breaking"
        - "topic: deprecation"
    - title: API
      labels:
        - "module: api"
    - title: Core
      labels:
        - "module: core"
    - title: Graph Passes
      labels:
        - "module: passes"
    - title: Bug fixes
      labels:
        - "topic: bug fix"
    - title: Build, CI and Tests
      labels:
        - "module: build"
        - "module: CI pipelines"
        - "module: test"
    - title: Documentation
      labels:
        - "module: docs"
    - title: Other Changes
      labels:
        - "*"
