# Copyright (c) ONNX Project Contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "onnx-ir"
SPDX-PackageSupplier = "onnx-technical-discuss@lists.lfaidata.foundation"
SPDX-PackageDownloadLocation = "onnx.ai"

[[annotations]]
path = [
    ".editorconfig",
    ".gitignore",
    "**/*.css",
    "**/*.ipynb",
    "**/*.md",
    "**/*.rst",
    "**/*.toml",
    "**/*.yml",
    "CODEOWNERS",
    "MANIFEST.in",
    "requirements*.txt",
    "requirements/**/*.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/onnx_ir/_thirdparty/asciichartpy.py"
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2016 Igor Kroitor",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tests/public_api_test.py"
precedence = "aggregate"
SPDX-FileCopyrightText = [
    """
    From PyTorch:

    Copyright (c) 2016-     Facebook, Inc            (Adam Paszke)
    Copyright (c) 2014-     Facebook, Inc            (Soumith Chintala)
    Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
    Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
    Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
    Copyright (c) 2011-2013 NYU                      (Clement Farabet)
    Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
    Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
    Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)

    From Caffe2:

    Copyright (c) 2016-present, Facebook Inc. All rights reserved.

    All contributions by Facebook:
    Copyright (c) 2016 Facebook Inc.

    All contributions by Google:
    Copyright (c) 2015 Google Inc.
    All rights reserved.

    All contributions by Yangqing Jia:
    Copyright (c) 2015 Yangqing Jia
    All rights reserved.

    All contributions by Kakao Brain:
    Copyright 2019-2020 Kakao Brain

    All contributions by Cruise LLC:
    Copyright (c) 2022 Cruise LLC.
    All rights reserved.

    All contributions by Tri Dao:
    Copyright (c) 2024 Tri Dao.
    All rights reserved.

    All contributions by Arm:
    Copyright (c) 2021, 2023-2024 Arm Limited and/or its affiliates

    All contributions from Caffe:
    Copyright(c) 2013, 2014, 2015, the respective contributors
    All rights reserved.

    All other contributions:
    Copyright(c) 2015, 2016 the respective contributors
    All rights reserved.

    Caffe2 uses a copyright model similar to Caffe: each contributor holds
    copyright over their contributions to Caffe2. The project versioning records
    all such contribution and copyright details. If a contributor wants to further
    mark their specific copyright on a particular contribution, they should
    indicate their copyright solely in the commit message of the change when it is
    committed.

    All rights reserved.
    """
]
SPDX-License-Identifier = "BSD-3-Clause"
