# Copyright (c) ONNX Project Contributors
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "onnx"
SPDX-PackageSupplier = "onnx-technical-discuss@lists.lfaidata.foundation"
SPDX-PackageDownloadLocation = "onnx.ai"

[[annotations]]
path = "codecov.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".github/**/**.md", ".github/pull_request_template.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**/**.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) ONNX Project Contributors"
SPDX-License-Identifier = "Apache-2.0"
