# Copyright (c) ONNX Project Contributors
# SPDX-License-Identifier: Apache-2.0
"""Shape inference operators.

This module imports all operator shape inference functions to ensure
they are registered with the global registry.
"""

# Import to trigger registration
from onnx_ir.shape_inference._ops import (
    _arg,
    _attention,
    _cast,
    _concat,
    _constant,
    _constant_of_shape,
    _control_flow,
    _conv,
    _conv_transpose,
    _depth_space,
    _dropout,
    _elementwise,
    _expand,
    _gather,
    _gemm,
    _loss,
    _matmul,
    _normalization,
    _onehot,
    _pad,
    _pooling,
    _random,
    _range,
    _reduce,
    _reshape,
    _resize,
    _rnn,
    _scatter,
    _sequence,
    _shape_ops,
    _signal,
    _slice,
    _softmax,
    _spatial,
    _split,
    _squeeze,
    _tile,
    _topk,
    _transpose,
    _unary,
    _where,
)

__all__ = [
    "_arg",
    "_attention",
    "_cast",
    "_concat",
    "_constant",
    "_constant_of_shape",
    "_control_flow",
    "_conv",
    "_conv_transpose",
    "_depth_space",
    "_dropout",
    "_elementwise",
    "_expand",
    "_gather",
    "_gemm",
    "_loss",
    "_matmul",
    "_normalization",
    "_onehot",
    "_pad",
    "_pooling",
    "_random",
    "_range",
    "_reduce",
    "_reshape",
    "_resize",
    "_rnn",
    "_scatter",
    "_sequence",
    "_shape_ops",
    "_signal",
    "_slice",
    "_softmax",
    "_spatial",
    "_split",
    "_squeeze",
    "_tile",
    "_topk",
    "_transpose",
    "_unary",
    "_where",
]
